version: '3'
services:
  application:
    image: spring-boot-mysql-app 
    ports: 
      - "8080:8080"
    networks:
      - springboot-db-net 
    depends_on:
      - mysqldb 
    volumes:
      - /data/springboot-app 

  mysqldb:
    image: mysql:5.7
    networks:
      - springboot-db-net 
    environment:
      - MYSQL_ROOT_PASSWORD=Zarina0708.210104075
      - MYSQL_DATABASE=db
    volumes:
      -/data/mysql
networks:
  springboot-db-net:
  
    